### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Ragnnn** [irlndts/go-discogs#31] opened 2019-10-28 15:27 UTC
Hi,

I've been playing around with Discogs' API and found your project which I wanted to use for a personal project.
So first thanks for the work, simple and efficient (+1)

But your Search does not work because you set every single parameters even with an empty string, and it looks like Discogs handles these parameters if declared and doesn't check if it's empty.

Example:
This request below gives the default result of a search, just like if you set no paramter
```
GET https://api.discogs.com/database/search?anv&artist&barcode&catno&contributor&country&credit&format&genre&label&page=0&per_page=10&q&style&submitter&year&release_title&track&type=artist&title=eminem
```
This one do give Eminem as an artist
```
GET https://api.discogs.com/database/search?type=artist&title=eminem
```

**Comment by irlndts** [comment] 2019-10-29 10:42
Hi, thanks for your interest, I appreciate it.
The problem is fixed in #32

**Closed as completed by irlndts** 2019-10-29 10:42 UTC
